on:
  pull_request:
    branches:
      - develop
    types:
      - closed

name: Deploy backend in uat env
jobs:
  deploy-uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Update repo
        run: ssh staging 'cd bot-whatsapp-order-backend ; git checkout develop ; git fetch'

      - name: Deploy in dev
        run: ssh staging 'cd bot-whatsapp-order-backend ; sudo npm install && sudo npm run build && pm2 reload ecosystem.config.js --only dev'

      - name: Pm2 information
        run: ssh staging 'pm2 list'
